[data]
v = { command = "./scripts/versions", format = "json", watch = [
	"packages/agave/package.nix",
	"packages/agave-2_0/package.nix",
	"packages/agave-2_1/package.nix",
	"packages/agave-2_2/package.nix",
	"packages/agave-2_3/package.nix",
	"packages/agave-3_0/package.nix",
	"packages/agave-3_1/package.nix",
	"packages/agave-4_0/package.nix",
	"packages/agave-4_1/package.nix",
	"packages/agave-4_2/package.nix",
	"packages/agave-4_3/package.nix",
	"packages/dylint/package.nix",
	"packages/cargo-interactive-update/package.nix",
	"packages/codex-cli/package.nix",
	"packages/deno/package.nix",
	"packages/godot/package.nix",
	"packages/gpg-suite/package.nix",
	"packages/kani/package.nix",
	"packages/keyring/package.nix",
	"packages/knope/package.nix",
	"packages/mdt/package.nix",
	"packages/monochange/package.nix",
	"packages/nordvpn/package.nix",
	"packages/ollama/package.nix",
	"packages/patrol_cli/package.nix",
	"packages/pina/package.nix",
	"packages/pnpm/package.nix",
	"packages/pnpm-10/package.nix",
	"packages/pnpm-11/package.nix",
	"packages/racket-minimal/package.nix",
	"packages/sbpf-linker/package.nix",
	"packages/solana-verify/package.nix",
	"packages/steam/package.nix",
	"packages/surfpool/package.nix",
	"packages/wait-for-them/package.nix",
	"packages/zoom/package.nix",
] }

[exclude]
markdown_codeblocks = true
