[data]
v = { command = "./scripts/versions", format = "json", watch = [
	"packages/agave/package.nix",
	"packages/agave-2_0/package.nix",
	"packages/agave-2_1/package.nix",
	"packages/agave-2_2/package.nix",
	"packages/agave-2_3/package.nix",
	"packages/agave-3_0/package.nix",
	"packages/cargo-interactive-update/package.nix",
	"packages/codex-cli/package.nix",
	"packages/codexbar/package.nix",
	"packages/cursor-cli/package.nix",
	"packages/godot/package.nix",
	"packages/gpg-suite/package.nix",
	"packages/knope/package.nix",
	"packages/mdt/package.nix",
	"packages/nordvpn/package.nix",
	"packages/pina/package.nix",
	"packages/pnpm-standalone/package.nix",
	"packages/racket-minimal/package.nix",
	"packages/steam/package.nix",
	"packages/surfpool/package.nix",
	"packages/zoom/package.nix",
] }

[exclude]
markdown_codeblocks = true
